version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust:stretch
    steps:
      - checkout
      - run: echo 'pass build'
  test:
    docker:
      - image: circleci/rust:stretch
    steps:
      - checkout
      - run: echo 'pass test'
        
workflows:
  commit-workflow:
    jobs:
      - build
      - test